- codegen/parser/endpoints/endpoint.py
- codegen/templates/client/_param.py.jinja
- githubkit/rest/actions.py
Just remove the duplicate field in body overload to avoid `SyntaxError`. fix #16
> Fix: duplicate field name in path and body

- codegen/__init__.py
- codegen/config.py
- pyproject.toml
> Fix: `rest_description_source` typo

- githubkit/core.py
The `pydantic_encode` function doesn't work with `dict`. `list`, `str`, `int`, etc. objects out of the box, so I had to make a small wrapper to get it to work. I haven't tested this extensively, but I know it isn't throwing a validation error anymore.
Closes #21.
> Fix: Add wrapper to prep data for JSON encoding

- githubkit/auth/app.py
Since GitHub application IDs are always integers, it would be nice if the `AppInstallationAuthStrategy` (and similar) classes allowed for `int` types in addition to `str`. We could just replace `str` with `int`, but that wouldn't be backwards compatible, so I decided to just keep both. I can update that though if only using `int` is preferred.
> Feature: allow integer app id

- codegen/__init__.py
- codegen/config.py
- codegen/templates/client/_request.py.jinja
- codegen/templates/client/client.py.jinja
- pyproject.toml
This PR is related to #9  and adds a REST-API-VERSION property for each Rest Client (at first I added it to the RestNamespace but that resulted in circular dependencies, maybe another place is better suited?) and adds an appropriate header when doing requests.
Tested this in my own project using githubkit as there are no tests available.
I did not regenerate the classes itself as this would clutter the PR.
> Add support for REST-API-VERSION based on the used schema

- githubkit/utils.py
Example repro:
```python
from datetime import datetime, timezone
import asyncio
from githubkit import GitHub
async def main():
github = GitHub()
now = datetime.now(timezone.utc)
await github.rest.checks.async_create(
"example",
"repo",
data={
"name": "name",
"head_sha": "0000000000000000000000000000000000000000",
"external_id": "0000000000000000000000000000000000000000",
"status": "completed",
"conclusion": "failure",
"started_at": now,
"completed_at": now,
"output": {
"title": "some title",
"summary": "some summary",
"annotations": [
{
"path": "file.txt",
"start_line": 1,
"end_line": 1,
"start_column": 1,
"annotation_level": "failure",
"message": "some message",
}
],
},
},
)
asyncio.run(main())
```
Running with githubkit version 0.9.8:
```
$ python3 file.py
Traceback (most recent call …
```
> Fix: Remove `UNSET` objects from lists

- pyproject.toml
Hey! 👋  I found some inconsistencies in the OpenAPI schema for the auto-merge definition (see the comments for a link to the upstream issue) and added temporary workarounds here until GitHub has fixed their definition.
> Fix: auto-merge commit_title/commit_message type

- codegen/config.py
- codegen/parser/__init__.py
- codegen/parser/endpoints/__init__.py
- codegen/parser/endpoints/parameter.py
- codegen/parser/endpoints/request_body.py
- codegen/parser/endpoints/response.py
- codegen/parser/schemas/__init__.py
- codegen/parser/schemas/any_schema.py
- codegen/parser/schemas/bool_schema.py
- codegen/parser/schemas/enum_schema.py
- codegen/parser/schemas/float_schema.py
- codegen/parser/schemas/int_schema.py
- codegen/parser/schemas/list_schema.py
- codegen/parser/schemas/model_schema.py
- codegen/parser/schemas/none_schema.py
- codegen/parser/schemas/string_schema.py
- codegen/parser/schemas/union_schema.py
- codegen/parser/utils.py
- poetry.lock
- pyproject.toml
I've read through #38 and got excited to check and see what it would take to add support for Pydantic 2.
The first issue I encountered was that `openapi-schema-pydantic` only supports Pydantic 1, and hasn't been actively developed for a while. [openapi-pydantic](https://github.com/mike-oakley/openapi-pydantic) is a fork of openapi-schema-pydantic that has been updated with support for both Pydantic 1 and 2, and seems to be more actively maintained.
I might be jumping the gun here, so if this is not the way that you've planned to tackle Pydantic2 support, feel free to close this PR.
> Feature: Change to Pydantic 2 compatible openapi schema parser

- githubkit/auth/_url.py
`APP_ROUTES` contains an `r"/app"` entry to match for the `/app` route. This will also match repositories which start with `app` causing `require_app_auth` to return true.
This change adjusts the `/app` regex to match at the beginning of the string and not anywhere within the url.path
> Bug: fix `require_app_auth` matches unexpected routes

- githubkit/utils.py
As discussed in #47, I'm proposing this change to avoid issues when GitHub schema is not reliable regarding properties that are nullable or not.
Semantically, it's equivalent to say that "*if the property is not `required` in the OpenAPI schema, we allow it to have the value `null`*".
> Feature: Tweak `Missing` type to implicitly allow `None` values

- githubkit/config.py
- githubkit/core.py
- githubkit/github.py
- pyproject.toml
Closes #61 
Adds [RFC9111 HTTP caching](https://www.rfc-editor.org/rfc/rfc9111.html), which caches responses that the server suggests reusing.
If we want to provide a way to disable caching, perhaps we should add something like `http_cache` boolean to the `GitHub` class?
> Feature: Add caching for HTTP responses

- codegen/parser/utils.py
- githubkit/rest/code_scanning.py
- githubkit/rest/codespaces.py
- githubkit/rest/copilot.py
- githubkit/rest/licenses.py
- githubkit/rest/models.py
- githubkit/rest/orgs.py
- githubkit/rest/repos.py
- githubkit/rest/secret_scanning.py
- githubkit/rest/security_advisories.py
- githubkit/rest/types.py
- pyproject.toml
While parsing OpenAPI spec for 2022-11-28:
```
codegen/parser/utils.py", line 105, in merge_dict
del old[key]
~~~^^^^^
KeyError: 'enum'
```
Signed-off-by: Joao Eduardo Luis \<joao@1e3ms.io>
P.S.: This was hit while running `python -m codegen` on the current master branch (620e08f26274c6fd51339078c4fbfd29c80e702f), which was surprising. I'm not ruling out this might be a problem with my environment, but I suspect this might be a corner case somewhere with the schema.
> Fix: `copilot seat details` schema fixed

- githubkit/rest/models.py
- githubkit/rest/types.py
- pyproject.toml
A similar bug was fixed by: https://github.com/yanyongyu/githubkit/commit/67d4bf55278d65308f57d98044848ff5c4a6c032
So I did the same things and it now works locally.
Fixes #64
> Fix: `PullRequestSimplePropHead` label field can be `null`

- githubkit/webhooks/models.py
- pyproject.toml
According to the webhook events we're getting sent by github, the changed field_type can be "labels" as well, but this doesn't seem to be covered by the octokit schema.
As an example, take the following snippet:
```
"action": "edited",
"projects_v2_item": {
"id": 12345,
"node_id": "PVTI_ASDASD",
"project_node_id": "PVT_ASDASD",
"content_node_id": "I_ASDASD",
"content_type": "Issue",
"creator": {
"login": "jecluis",
[...]
},
"created_at": "2023-12-18T06:44:23Z",
"updated_at": "2023-12-18T16:21:38Z",
"archived_at": null
},
"changes": {
"field_value": {
"field_node_id": "PVTF_ASDASD",
"field_type": "labels"
}
},
```
Signed-off-by: Joao Eduardo Luis \<joao@1e3ms.io>
> Fix: project v2 item field change type may be labels

- .gitignore
- githubkit/core.py
- githubkit/exception.py
- githubkit/github.py
- githubkit/graphql/__init__.py
- githubkit/graphql/models.py
I've added a `RateLimitExceededError` class.
This exception provides the time you have to wait before retrying, which simplifies implementing rate limiting.
> Feature: support detecting rate limit exceeded

- README.md
- githubkit/config.py
- githubkit/core.py
- githubkit/github.py
- githubkit/log.py
- githubkit/retry.py
- githubkit/typing.py
This PR introduces a mechanism that limits the number of concurrent requests.
Additionally, if a `RateLimitExceeded` response is encountered, new requests are not started for a while.
I'm not sure if halting the new requests is really needed, but it seems the right thing to do.
The print statements are there currently for seeing that the mechanism works.
Should they be replace with a logger? or removed entirely?
Related to #66
> Feature: auto retry when rate limit exceeded or server error encountered

- githubkit/auth/app.py
This makes the cache multi-app aware, and so that it can handle JWT tokens from multiple apps
> Bug: app auth cache keys missing app_id

- githubkit/exception.py
- githubkit/response.py
> Feature: add reason phrase to response and exceptions

- README.md
> Docs: add weakref warning

- README.md
- envs/pydantic-v1/poetry.lock
- envs/pydantic-v2/poetry.lock
- envs/test/poetry.lock
- githubkit/__init__.py
- githubkit/auth/__init__.py
- githubkit/auth/oauth.py
> Feature: support oauth token auth

- pyproject.toml
GitHub generates `check_suite` webhook events with `check_suite.app.events` containing illegal event names. I filed this upstream at https://github.com/github/rest-api-description/issues/3775.
E.g., I'm seeing events like:
```json
{
"check_suite": {
...
"app": {
...
"events": [
"branch_protection_configuration",  // <-- Oops!
"branch_protection_rule",
"check_run",
"check_suite",
"issue_comment",
"member",
"membership",
"merge_group",
"organization",
"pull_request",
"pull_request_review",
"pull_request_review_comment",
"pull_request_review_thread",
"push",
"repository",
"repository_ruleset",  // <-- Oops!
"status",
"team",
"team_add",
"workflow_job",
"workflow_run"
]
},
...
```
I believe the best course of action would be for GitHubKit to not validate the `check_suite.app.events` array …
> Fix: Tolerate any string values in github app events array schema

- README.md
> Docs: update type hints in examples

- README.md
- githubkit/exception.py
- githubkit/github.py
- githubkit/graphql/__init__.py
- githubkit/graphql/paginator.py
- tests/test_graphql/test_graphql.py
resolve #112 
```python
from githubkit import GitHub
g = GitHub("your token here")
query = """
query($owner:String!, $repo: String!, $cursor: String) {
repository(owner:$owner, name:$repo) {
issues(first: 10, after: $cursor) {
nodes {
number
}
pageInfo {
hasNextPage
endCursor
}
}
}
}
"""
for result in g.graphql.paginate(query, {"owner": "owner", "repo": "repo"}):
for issue in result["repository"]["issues"]["nodes"]:
print(issue)
```
> Feature: add graphql pagination support

- codegen/templates/webhooks/_namespace.py.jinja
- githubkit/versions/ghec_v2022_11_28/webhooks/_namespace.py
- githubkit/versions/v2022_11_28/webhooks/_namespace.py
When calling the `parse` functions for webhooks, we don't always control where the `name` parameter comes from.
In my case, I retrieve it from a HTTP request's header and the type is simply `str`:
```python
name: str = headers['X-GitHub-Event']
event = parse(name, b"")
```
And pyright complains with the following:
`error: Type of "event" is unknown (reportUnknownVariableType)`
`error: No overloads for "parse" match the provided arguments (reportCallIssue)`
However, since `parse` and `parse_obj` check for `name` to be part of `VALID_EVENT_NAMES` it looks safe to me to allow for plain `str` to be passed.
Let me know what you think.
> Feature: allow parsing webhook with event name of type str

- README.md
- githubkit/auth/oauth.py
> Feature: improve refresh token usage and docs

- githubkit/auth/app.py
Client ID is recommended now when generating jwt token.
Reference: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app
> Feature: support app jwt auth using client id

- codegen/parser/schemas/schema.py
As a user of Pydantic V1, there are some models that use constraints on Pydantic List fields that fail on import:
```
ValueError: On field "annotations" the following field constraints are set but not enforced: max_length. 
For more details see https://docs.pydantic.dev/usage/schema/#unenforced-field-constraints
```
On the root of the project, with the venv populated and activated:
```
$ pip install "pydantic<2"
$ python
> import githubkit.versions.v2022_11_28.models.group_0932
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/juan/Documentos/OpenSource/githubkit/githubkit/versions/v2022_11_28/models/group_0932.py", line 21, in <module>
class ReposOwnerRepoCheckRunsPostBodyPropOutput(GitHubModel):
File "pydantic/main.py", line 197, in …
```
> Fix: model list schema constraints error when using Pydantic V1

- githubkit/versions/ghec_v2022_11_28/models/group_0213.py
- githubkit/versions/ghec_v2022_11_28/types/group_0213.py
- githubkit/versions/v2022_11_28/models/group_0190.py
- githubkit/versions/v2022_11_28/types/group_0190.py
- pyproject.toml
When using `compare_commits`, a `diff-entry` listed in the `files` property might have `blob_url` and `raw_url` set to `null`
I encountered this issue when comparing commits that made a change to a submodule. It might be the only case where those two properties may be null.
```python
gh.rest.repos.compare_commits(
'jqlang',
'jq',
'481167c8f186d534b2cef0e8a7d6a4d6dbc45d6b...092fef740a0d1a0ddf61cf9e7af88915071c0705',
).parsed_data
```
:arrow_down: 
```
pydantic_core._pydantic_core.ValidationError: 3 validation errors for CommitComparison
files.literal[<UNSET>]
Input should be <UNSET> [type=literal_error, input_value=[{'sha': 'cca857c64d3d678... --leak-check=full \\'}], input_type=list]
For further information visit https://errors.pydantic.dev/2.8/v/literal_error …
```
> Fix: diff-entry's blob_url and raw_url may be null

- README.md
- githubkit/graphql/__init__.py
- tests/test_graphql/test_endpoint.py
> Fix: ghes graphql endpoint error

- docs/usage/error-handling.md
- githubkit/core.py
- githubkit/exception.py
`RequestTimeout` and `RequestFailed` are subclass of `RequestError` now.
> Feature: improve request error structure

- docs/installation.md
- docs/usage/configuration.md
- githubkit/config.py
- githubkit/core.py
- githubkit/github.py
- githubkit/throttling.py
- poetry.lock
- pyproject.toml
This pr adds the basic request [concurrency throttling](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits) logic. The [pause between mutative requests](https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28#pause-between-mutative-requests) logic is not implemented.
fix #66
> Feature: add basic throttling logic

- docs/usage/rest-api.md
> Docs: add model dump guide

- pyproject.toml
In versions prior to typing-extensions 4.11.0, the following error occurs
```bash
Traceback (most recent call last):
File "/Users/user/Documents/git/paddle-tools/autoTable/test.py", line 1, in <module>
from githubkit import GitHub
File "/Users/user/miniconda3/envs/py312/lib/python3.12/site-packages/githubkit/__init__.py", line 17, in <module>
from .core import GitHubCore as GitHubCore
File "/Users/user/miniconda3/envs/py312/lib/python3.12/site-packages/githubkit/core.py", line 44, in <module>
class GitHubCore(Generic[A]):
File "/Users/user/miniconda3/envs/py312/lib/python3.12/site-packages/githubkit/core.py", line 342, in GitHubCore
) -> Response[T]: ...
~~~~~~~~^^^
File "/Users/user/miniconda3/envs/py312/lib/python3.12/typing.py", line 384, in inner
return func(*args, **kwds) …
```
> Fix: typevar with default cause error in `typing-extensions<4.11.0`

- githubkit/versions/ghec_v2022_11_28/models/group_0266.py
- githubkit/versions/ghec_v2022_11_28/models/group_0836.py
- githubkit/versions/ghec_v2022_11_28/models/group_0837.py
- githubkit/versions/ghec_v2022_11_28/models/group_0838.py
- githubkit/versions/ghec_v2022_11_28/types/group_0266.py
- githubkit/versions/ghec_v2022_11_28/types/group_0836.py
- githubkit/versions/ghec_v2022_11_28/types/group_0837.py
- githubkit/versions/ghec_v2022_11_28/types/group_0838.py
- githubkit/versions/v2022_11_28/models/group_0229.py
- githubkit/versions/v2022_11_28/models/group_0778.py
- githubkit/versions/v2022_11_28/models/group_0779.py
- githubkit/versions/v2022_11_28/models/group_0780.py
- githubkit/versions/v2022_11_28/types/group_0229.py
- githubkit/versions/v2022_11_28/types/group_0778.py
- githubkit/versions/v2022_11_28/types/group_0779.py
- githubkit/versions/v2022_11_28/types/group_0780.py
- pyproject.toml
The webhook payload for the `workflow_run` event types (completed, in-progress & requested) each define the id and number of pull requests as `number` where they clearly should be `integer` values.
- This issue has been reported to GitHub as github/rest-api-description#4408
- The regenerated models include the latest updates (specifically github/rest-api-description#4404)
> Fix: workflow_run pull_requests id/number types

- docs/usage/authentication.md
- docs/usage/rest-api.md
- docs/usage/unit-test.md
> Docs: update response types for json type inspect

- codegen/templates/versions/rest.py.jinja
- docs/usage/graphql.md
- docs/usage/rest-api.md
- githubkit/paginator.py
- githubkit/rest/paginator.py
- githubkit/versions/rest.py
- tests/test_rest/test_call.py
> Feature: support `link` header pagination 

- githubkit/versions/ghec_v2022_11_28/models/group_0261.py
- githubkit/versions/ghec_v2022_11_28/types/group_0261.py
- githubkit/versions/v2022_11_28/models/group_0221.py
- githubkit/versions/v2022_11_28/types/group_0221.py
- pyproject.toml
> Feature: make GitUser's `date` field to be date-time 

- pyproject.toml
Adds missing values to dependabot-alert-with-repository and code-scanning-alert-classification.
> Fix: add missing enum values for dependabot and code scanning alerts

- docs/usage/configuration.md
- githubkit/config.py
- githubkit/core.py
- githubkit/github.py
This PR should pass-through the `verify` argument to the underlying HTTPX `Client` or `AsyncClient`.
https://www.python-httpx.org/advanced/ssl/
- Resolves #208
> Feature: add httpx `verify` config

- codegen/pyproject.toml
- codegen/templates/rest/_docstring.py.jinja
- codegen/templates/rest/client.py.jinja
- pyproject.toml
- scripts/run-codegen.sh
> Docs: add more info to rest api methods' docstring

- githubkit/rest/paginator.py
- tests/test_rest/test_call.py
> Fix: rest paginator iteration error

- githubkit/versions/ghec_v2022_11_28/models/group_0020.py
- githubkit/versions/ghec_v2022_11_28/types/group_0020.py
- githubkit/versions/v2022_11_28/models/group_0020.py
- githubkit/versions/v2022_11_28/types/group_0020.py
- pyproject.toml
> Fix: repo owner can be null when account deleted

- codegen/templates/rest/_param.py.jinja
- codegen/templates/rest/_request.py.jinja
- githubkit/core.py
- githubkit/response.py
- tests/test_rest/test_call.py
> Feature: support streaming response data

- githubkit/versions/ghec_v2022_11_28/models/group_0525.py
- githubkit/versions/ghec_v2022_11_28/types/group_0525.py
- githubkit/versions/v2022_11_28/models/group_0458.py
- githubkit/versions/v2022_11_28/types/group_0458.py
- githubkit/versions/versions.lock
- pyproject.toml
> Fix: discussion answer parent id type
